/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    plants: Plant;
    plantCategories: PlantCategory;
    services: Service;
    portfolios: Portfolio;
    testimonials: Testimonial;
    teamMembers: TeamMember;
    mediaMentions: MediaMention;
    contactSubmissions: ContactSubmission;
    search: Search;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    plants: PlantsSelect<false> | PlantsSelect<true>;
    plantCategories: PlantCategoriesSelect<false> | PlantCategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    portfolios: PortfoliosSelect<false> | PortfoliosSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    teamMembers: TeamMembersSelect<false> | TeamMembersSelect<true>;
    mediaMentions: MediaMentionsSelect<false> | MediaMentionsSelect<true>;
    contactSubmissions: ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    siteSettings: SiteSetting;
    emailSettings: EmailSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    emailSettings: EmailSettingsSelect<false> | EmailSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  role: 'admin' | 'editor';
  profilePicture?: (number | null) | Media;
  /**
   * Enable to require two-factor authentication for this user. The user will choose their preferred method on next login.
   */
  twoFactorEnabled?: boolean | null;
  /**
   * Set automatically when the user completes 2FA setup
   */
  twoFactorMethod?: ('email' | 'authenticator') | null;
  twoFactorSecret?: string | null;
  twoFactorBackupCodes?:
    | {
        hash?: string | null;
        id?: string | null;
      }[]
    | null;
  twoFactorEmailCode?: string | null;
  twoFactorEmailCodeExpiresAt?: string | null;
  /**
   * Unix timestamp when the current 2FA admin session expires
   */
  twoFactorSessionExpires?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Auto-generated from title, e.g. about-us
   */
  slug: string;
  /**
   * Select the matching frontend page to show page-specific content fields.
   */
  pageType?:
    | (
        | 'home'
        | 'about'
        | 'why-garden'
        | 'contact'
        | 'media'
        | 'educational-program'
        | 'garden-product'
        | 'landscaping-consultancy'
        | 'movement'
        | 'privacy-policy'
      )
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    backgroundImage?: (number | null) | Media;
    backgroundVideo?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  homeSections?: {
    whyGarden?: {
      eyebrow?: string | null;
      heading?: string | null;
      items?:
        | {
            itemId: string;
            tag: string;
            description?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
          }[]
        | null;
    };
    aboutExcerpt?: {
      eyebrow?: string | null;
      title?: string | null;
      content?: string | null;
      image?: (number | null) | Media;
      cta?: {
        label?: string | null;
        url?: string | null;
      };
    };
    whatWeDo?: {
      eyebrow?: string | null;
      heading?: string | null;
      cards?:
        | {
            title: string;
            summary?: string | null;
            image?: (number | null) | Media;
            href: string;
            id?: string | null;
          }[]
        | null;
    };
    gardenVisit?: {
      heading?: string | null;
      description?: string | null;
      mapLabel?: string | null;
      slides?:
        | {
            image?: (number | null) | Media;
            alt?: string | null;
            caption?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    finalCta?: {
      heading?: string | null;
      highlightedText?: string | null;
      description?: string | null;
      backgroundImage?: (number | null) | Media;
      primaryCta?: {
        label?: string | null;
        url?: string | null;
      };
      secondaryCta?: {
        label?: string | null;
        url?: string | null;
      };
    };
  };
  aboutSections?: {
    story?: {
      eyebrow?: string | null;
      heading?: string | null;
      image?: (number | null) | Media;
      paragraphs?:
        | {
            text?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    values?:
      | {
          icon?: string | null;
          title: string;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    timeline?:
      | {
          year: string;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    teamIntro?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
    };
    cta?: {
      heading?: string | null;
      description?: string | null;
    };
  };
  whyGardenSections?: {
    items?:
      | {
          itemId: string;
          tag: string;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    feedback?: {
      eyebrow?: string | null;
      heading?: string | null;
      content?: string | null;
    };
    stories?:
      | {
          storyId: string;
          label?: string | null;
          title: string;
          description?: string | null;
          image?: (number | null) | Media;
          linkText?: string | null;
          linkUrl?: string | null;
          color?: string | null;
          id?: string | null;
        }[]
      | null;
    storiesHeading?: string | null;
    resources?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
      plantStoryHeading?: string | null;
      plantStoryDescription?: string | null;
      plantStoryButtonText?: string | null;
      plantStoryImage?: (number | null) | Media;
      blogHeading?: string | null;
      blogLinks?:
        | {
            label: string;
            url: string;
            colorClass?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  contactSections?: {
    formIntro?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
    };
  };
  mediaSections?: {
    cardImages?:
      | {
          image?: (number | null) | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  serviceIndexSections?: {
    cta?: {
      icon?: string | null;
      heading?: string | null;
      description?: string | null;
      primaryCta?: {
        label?: string | null;
        url?: string | null;
      };
      secondaryCta?: {
        label?: string | null;
        url?: string | null;
      };
    };
  };
  privacyPolicySections?: {
    effectiveDate?: string | null;
    sections?:
      | {
          heading: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            style?: ('centered' | 'left' | 'overlay') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            columns?: ('1' | '2' | '3') | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            media: number | Media;
            caption?: string | null;
            layout?: ('fullWidth' | 'inset' | 'floatLeft' | 'floatRight') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            heading: string;
            description?: string | null;
            primaryButtonText?: string | null;
            primaryButtonLink?: string | null;
            secondaryButtonText?: string | null;
            secondaryButtonLink?: string | null;
            backgroundColor?: ('green' | 'white' | 'beige') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('carousel' | 'grid' | 'masonry') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            services?: (number | Service)[] | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceCards';
          }
        | {
            heading?: string | null;
            testimonials?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  authorPhoto?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            embedUrl: string;
            label?: string | null;
            height?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapBlock';
          }
        | {
            heading?: string | null;
            stats?:
              | {
                  number: string;
                  label: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  serviceCategory: 'managed-it' | 'cloud' | 'security' | 'software' | 'data' | 'support';
  shortDescription?: string | null;
  coverImage?: (number | null) | Media;
  tagline?: string | null;
  longDescription?: string | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  imageSlides?:
    | {
        image?: (number | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  whyChoose?:
    | {
        icon?: string | null;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional override for product/program CTAs.
   */
  whatsappNumber?: string | null;
  ctaLinks?:
    | {
        label: string;
        url: string;
        style?: ('text' | 'primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            backgroundVideo?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            style?: ('centered' | 'left' | 'overlay') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            columns?: ('1' | '2' | '3') | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            media: number | Media;
            caption?: string | null;
            layout?: ('fullWidth' | 'inset' | 'floatLeft' | 'floatRight') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            heading: string;
            description?: string | null;
            primaryButtonText?: string | null;
            primaryButtonLink?: string | null;
            secondaryButtonText?: string | null;
            secondaryButtonLink?: string | null;
            backgroundColor?: ('green' | 'white' | 'beige') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('carousel' | 'grid' | 'masonry') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            testimonials?:
              | {
                  quote: string;
                  authorName: string;
                  authorRole?: string | null;
                  authorPhoto?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            stats?:
              | {
                  number: string;
                  label: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  publishedAt?: string | null;
  /**
   * Controls the order on the services listing page
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from title, e.g. tips-menanam-tomat
   */
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional structured blocks used by the bespoke article template for callouts and full-width images.
   */
  contentBlocks?:
    | {
        blockType: 'heading' | 'paragraph' | 'full-image' | 'callout';
        text?: string | null;
        title?: string | null;
        image?: (number | null) | Media;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedPosts?: (number | Post)[] | null;
  author: number | User;
  publishedAt: string;
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from category name
   */
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants".
 */
export interface Plant {
  id: number;
  commonName: string;
  scientificName: string;
  slug: string;
  plantFamily?: string | null;
  origin?: string | null;
  mainPhoto?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  careGuide?: {
    sunlight?: string | null;
    watering?: string | null;
    soil?: string | null;
    temperature?: string | null;
    humidity?: string | null;
  };
  ecologicalRole?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?:
    | {
        icon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  designersNote?: {
    quote?: string | null;
    author?: string | null;
  };
  plantType?: (number | PlantCategory)[] | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plantCategories".
 */
export interface PlantCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios".
 */
export interface Portfolio {
  id: number;
  projectName: string;
  slug: string;
  clientName?: string | null;
  location?: string | null;
  yearCompleted?: number | null;
  category?: ('Cloud Migration' | 'Security' | 'Managed IT' | 'Custom Software' | 'Data & Automation') | null;
  tagline?: string | null;
  area?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        label?: string | null;
        badge?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  plants?: (number | Plant)[] | null;
  relatedServices?: (number | Service)[] | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorRole?: string | null;
  authorPhoto?: (number | null) | Media;
  backgroundImage?: (number | null) | Media;
  displayOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  displayOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaMentions".
 */
export interface MediaMention {
  id: number;
  title: string;
  displayDate?: string | null;
  excerpt: string;
  source?: string | null;
  url?: string | null;
  image?: (number | null) | Media;
  displayOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages received via the contact form. Read-only — do not edit submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions".
 */
export interface ContactSubmission {
  id: number;
  senderName: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  status?: ('new' | 'read' | 'replied') | null;
  receivedOn: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'plants';
        value: number | Plant;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'plants';
          value: number | Plant;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'plants';
        value: number | Plant;
      } | null)
    | ({
        relationTo: 'plantCategories';
        value: number | PlantCategory;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'portfolios';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'teamMembers';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'mediaMentions';
        value: number | MediaMention;
      } | null)
    | ({
        relationTo: 'contactSubmissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  profilePicture?: T;
  twoFactorEnabled?: T;
  twoFactorMethod?: T;
  twoFactorSecret?: T;
  twoFactorBackupCodes?:
    | T
    | {
        hash?: T;
        id?: T;
      };
  twoFactorEmailCode?: T;
  twoFactorEmailCodeExpiresAt?: T;
  twoFactorSessionExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        backgroundImage?: T;
        backgroundVideo?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  homeSections?:
    | T
    | {
        whyGarden?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    itemId?: T;
                    tag?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
            };
        aboutExcerpt?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              content?: T;
              image?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
            };
        whatWeDo?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    summary?: T;
                    image?: T;
                    href?: T;
                    id?: T;
                  };
            };
        gardenVisit?:
          | T
          | {
              heading?: T;
              description?: T;
              mapLabel?: T;
              slides?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
            };
        finalCta?:
          | T
          | {
              heading?: T;
              highlightedText?: T;
              description?: T;
              backgroundImage?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
            };
      };
  aboutSections?:
    | T
    | {
        story?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              image?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        values?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        timeline?:
          | T
          | {
              year?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        teamIntro?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
            };
      };
  whyGardenSections?:
    | T
    | {
        items?:
          | T
          | {
              itemId?: T;
              tag?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        feedback?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
            };
        stories?:
          | T
          | {
              storyId?: T;
              label?: T;
              title?: T;
              description?: T;
              image?: T;
              linkText?: T;
              linkUrl?: T;
              color?: T;
              id?: T;
            };
        storiesHeading?: T;
        resources?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              plantStoryHeading?: T;
              plantStoryDescription?: T;
              plantStoryButtonText?: T;
              plantStoryImage?: T;
              blogHeading?: T;
              blogLinks?:
                | T
                | {
                    label?: T;
                    url?: T;
                    colorClass?: T;
                    id?: T;
                  };
            };
      };
  contactSections?:
    | T
    | {
        formIntro?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
            };
      };
  mediaSections?:
    | T
    | {
        cardImages?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  serviceIndexSections?:
    | T
    | {
        cta?:
          | T
          | {
              icon?: T;
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
            };
      };
  privacyPolicySections?:
    | T
    | {
        effectiveDate?: T;
        sections?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        heroBanner?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              buttonText?: T;
              buttonLink?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              columns?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButtonText?: T;
              primaryButtonLink?: T;
              secondaryButtonText?: T;
              secondaryButtonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        serviceCards?:
          | T
          | {
              heading?: T;
              services?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    authorPhoto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mapBlock?:
          | T
          | {
              embedUrl?: T;
              label?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    number?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  contentBlocks?:
    | T
    | {
        blockType?: T;
        text?: T;
        title?: T;
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedPosts?: T;
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants_select".
 */
export interface PlantsSelect<T extends boolean = true> {
  commonName?: T;
  scientificName?: T;
  slug?: T;
  plantFamily?: T;
  origin?: T;
  mainPhoto?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  careGuide?:
    | T
    | {
        sunlight?: T;
        watering?: T;
        soil?: T;
        temperature?: T;
        humidity?: T;
      };
  ecologicalRole?: T;
  benefits?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  designersNote?:
    | T
    | {
        quote?: T;
        author?: T;
      };
  plantType?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plantCategories_select".
 */
export interface PlantCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  serviceCategory?: T;
  shortDescription?: T;
  coverImage?: T;
  tagline?: T;
  longDescription?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  imageSlides?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  whyChoose?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  whatsappNumber?: T;
  ctaLinks?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        heroBanner?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              buttonText?: T;
              buttonLink?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              columns?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButtonText?: T;
              primaryButtonLink?: T;
              secondaryButtonText?: T;
              secondaryButtonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    authorPhoto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    number?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios_select".
 */
export interface PortfoliosSelect<T extends boolean = true> {
  projectName?: T;
  slug?: T;
  clientName?: T;
  location?: T;
  yearCompleted?: T;
  category?: T;
  tagline?: T;
  area?: T;
  description?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        label?: T;
        badge?: T;
        caption?: T;
        id?: T;
      };
  plants?: T;
  relatedServices?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorRole?: T;
  authorPhoto?: T;
  backgroundImage?: T;
  displayOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  displayOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaMentions_select".
 */
export interface MediaMentionsSelect<T extends boolean = true> {
  title?: T;
  displayDate?: T;
  excerpt?: T;
  source?: T;
  url?: T;
  image?: T;
  displayOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  senderName?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  receivedOn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        url: string;
        subLinks?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  tagline?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  showNewsletter?: boolean | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  /**
   * Optional phone number with country code, e.g. 15550104102
   */
  whatsappNumber?: string | null;
  email?: string | null;
  address?: string | null;
  mapsEmbedUrl?: string | null;
  /**
   * Umami analytics tracking ID
   */
  analyticsId?: string | null;
  socialMedia?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    linkedin?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure business email settings for Resend-powered auth and contact emails. API keys stay in environment variables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailSettings".
 */
export interface EmailSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * Used as the sender name in outgoing emails.
   */
  fromName?: string | null;
  /**
   * Use a sender address from a domain already verified in Resend. Required when email delivery is enabled.
   */
  fromEmail?: string | null;
  replyToEmail?: string | null;
  sendContactAdminNotification?: boolean | null;
  sendContactAutoReply?: boolean | null;
  /**
   * Who should receive contact form notifications.
   */
  adminRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  contactAdminSubjectPrefix?: string | null;
  contactAutoReplySubject?: string | null;
  contactAutoReplyIntro?: string | null;
  contactAutoReplySignature?: string | null;
  forgotPasswordSubject?: string | null;
  forgotPasswordIntro?: string | null;
  forgotPasswordSignature?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        subLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  showNewsletter?: T;
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  whatsappNumber?: T;
  email?: T;
  address?: T;
  mapsEmbedUrl?: T;
  analyticsId?: T;
  socialMedia?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
        tiktok?: T;
        linkedin?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailSettings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  enabled?: T;
  fromName?: T;
  fromEmail?: T;
  replyToEmail?: T;
  sendContactAdminNotification?: T;
  sendContactAutoReply?: T;
  adminRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  contactAdminSubjectPrefix?: T;
  contactAutoReplySubject?: T;
  contactAutoReplyIntro?: T;
  contactAutoReplySignature?: T;
  forgotPasswordSubject?: T;
  forgotPasswordIntro?: T;
  forgotPasswordSignature?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}